### ISSUE TITLE
PFSをNoeticでも使えるようにしたい

### ISSUE THREAD

**Issue by Kanazawanaoaki** [708yamaguchi/pr2_fingertip_sensors#78]
ros noeticで動いているhsrにpfsをusb接続で取り付けてセンサ値を読み込もうとしましたが
以下のエラーが発生して動きませんでした．  
https://github.com/Kanazawanaoaki/pr2_fingertip_sensors/commit/4d7a9024a0025c88479a229bdb3f43cde6b13a69 のように変更して無理やり一時的に動かすことはできました．noeticで動かすにはcatkin_install_python周りやpythonのモジュール部分を変更する必要があると思うので後で時間がある時に作業しようかなと思います．

```
$ rosrun pr2_fingertip_sensors parse_serial.py -p /dev/ttyACM0
Traceback (most recent call last):
  File "parse_serial.py", line 8, in <module>
    from pr2_fingertip_sensors.msg import PR2FingertipSensor
  File "/home/kanazawa/pr2_fingertip_ws/devel/lib/python3/dist-packages/pr2_fingertip_sensors/__init__.py", line 34, in <module>
    exec(__fh.read())
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'pfs'
```

**Comment by 708yamaguchi** [comment]
おそらく
https://github.com/708yamaguchi/pr2_fingertip_sensors/pull/91
で解決しているはずで、

僕のnoetic環境では動きました。
```
$ rosrun pr2_fingertip_sensors parse_serial.py -p /dev/ttyACM0
[INFO] [1700666651.725577]: current serial port list: ['/dev/ttyACM0']
[INFO] [1700666651.726811]: Serial<id=0x7faae16c3e50, open=True>(port='/dev/ttyACM0', baudrate=57600, bytesize=8, parity='N', stopbits=1, timeout=None, xonxoff=False, rtscts=False, dsrdtr=False)
```
